apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aks-periscope

bases:
- ../../base

images:
- name: periscope-linux
  newName: ${IMAGE_NAME}
  newTag: "${IMAGE_TAG}"
- name: periscope-windows
  newName: ${IMAGE_NAME}
  newTag: "${IMAGE_TAG}"

secretGenerator:
- name: azureblob-secret
  behavior: replace
  envs:
  - .env.secret
- name: acr-secret
  behavior: create
  files:
  - .dockerconfigjson=acr.dockerconfigjson

configMapGenerator:
- name: diagnostic-config
  behavior: merge
  envs:
  - .env.config

patches:
- target:
    kind: DaemonSet
  patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value: [{ name: acr-secret }]