apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aks-periscope
spec:
  template:
    spec:
      containers:
      - name: aks-periscope
        image: periscope-local
        imagePullPolicy: Never
