apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- daemon-set.yaml

secretGenerator:
- name: azureblob-secret
  behavior: replace
  envs:
  - .env.secret

configMapGenerator:
- name: diagnostic-config
  behavior: merge
  envs:
  - .env.config
