apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aks-diagnostic
  labels:
    app: aks-diagnostic
spec:
  selector:
    matchLabels:
      app: aks-diagnostic
  template:
    metadata:
      labels:
        app: aks-diagnostic
    spec:
      hostPID: true
      containers:
      - name: aks-diagnostic
        image: aksrepos.azurecr.io/staging/aks-diagnostic:v0.1
        securityContext:
          privileged: true
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/etc/azure-blob"
          name: azure-blob
          readOnly: true
        - mountPath: /aks-diagnostic
          name: aks-diagnostic-storage
      volumes:
      - name: azure-blob
        secret:
          secretName: azure-blob
      - name: aks-diagnostic-storage
        hostPath:
          path: /var/log/aks-diagnostic
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-blob
type: Opaque
data:
  accountName: # <accountName, base64 encoded>
  sasKey: # <saskey, base64 encoded>