apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aks-diagnostic
  labels:
    app: aks-diagnostic
spec:
  selector:
    matchLabels:
      app: aks-diagnostic
  template:
    metadata:
      labels:
        app: aks-diagnostic
    spec:
      hostPID: true
      containers:
      - name: aks-diagnostic
        image: aksrepos.azurecr.io/staging/aks-diagnostic:v0.1
        securityContext:
          privileged: true
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: containerlogs-config
        - configMapRef:
            name: kubeobjects-config
        - secretRef:
            name: azureblob-secret
        volumeMounts:
        - mountPath: /aks-diagnostic
          name: aks-diagnostic-storage
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "2000Mi"
            cpu: "1000m"
      volumes:
      - name: aks-diagnostic-storage
        hostPath:
          path: /var/log/aks-diagnostic
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Secret
metadata:
  name: azureblob-secret
type: Opaque
data:
  AZURE_BLOB_ACCOUNT_NAME: # <accountName, base64 encoded>
  AZURE_BLOB_SAS_KEY: # <saskey, base64 encoded>
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: containerlogs-config
data:
  DIAGNOSTIC_CONTAINERLOGS_NAMESPACE: kube-system
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: kubeobjects-config
data:
  DIAGNOSTIC_KUBEOBJECTS_NAMESPACE: kube-system