apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aks-periscope

resources:
- namespace.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- config-map.yaml
- crd.yaml
- daemon-set.yaml
- service-account.yaml

images:
  - name: mcr.microsoft.com/aks/periscope
    newTag: v0.6
