apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aks-periscope

resources:
- namespace.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- config-map.yaml
- crd.yaml
- daemon-set.yaml
- service-account.yaml

secretGenerator:
- name: azureblob-secret
  literals:
  # AZURE_BLOB_SAS_KEY: ?sv=&ss=&srt=&sp=&se=&st=&spr=&sig=
  - AZURE_BLOB_SAS_KEY=

generatorOptions:
  disableNameSuffixHash: true