# This is a basic workflow to help you get started with Actions
name: Building and Pushing to GHCR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  common:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - uses: actions/checkout@v3
    - name: Get Changelog Entry
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_depth: 10
        path: ./CHANGELOG.md
    - name: Get Version Info
      id: read_metadata
      run: |
        echo "Version: ${{ steps.changelog_reader.outputs.version }}"
        echo "Changes: ${{ steps.changelog_reader.outputs.changes }}"
        $owner = "${{ github.repository_owner }}".ToLower()
        $tagbase = "ghcr.io/$owner/aks/periscope:${{ steps.changelog_reader.outputs.version }}"
        echo "tagbase=$tagbase" >> $env:GITHUB_OUTPUT
    outputs:
      tagbase: ${{ steps.read_metadata.outputs.tagbase }}
  publish:
    runs-on: ${{ matrix.os }}
    needs: common
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-2019, windows-2022]
        include:
        - os: ubuntu-latest
          baseimage: 'mcr.microsoft.com/cbl-mariner/distroless/base:2.0'
          tagext: 'mariner2.0'
          extension: ''
        - os: windows-2019
          baseimage: 'mcr.microsoft.com/windows/nanoserver:ltsc2019'
          tagext: 'nanoserver2019'
          extension: '.exe'
        - os: windows-2022
          baseimage: 'mcr.microsoft.com/windows/nanoserver:ltsc2022'
          tagext: 'nanoserver2022'
          extension: '.exe'
    defaults:
      run:
        shell: pwsh
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Packages OCI Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to ghcr.io
      id: publish
      run: |
        $tag = "${{ needs.common.outputs.tagbase }}-${{ matrix.tagext }}"
        echo "tag-${{ matrix.os }}=$tag" >> $env:GITHUB_OUTPUT
        docker build -f ./builder/Dockerfile --build-arg BASE_IMAGE=${{ matrix.baseimage }} --build-arg EXTENSION=${{ matrix.extension }} -t $tag .
        docker push $tag
    outputs:
      linux: ${{ steps.publish.outputs.tag-ubuntu-latest }}
      win2019: ${{ steps.publish.outputs.tag-windows-2019 }}
      win2022: ${{ steps.publish.outputs.tag-windows-2022 }}
  update-manifest:
    runs-on: ubuntu-latest
    needs: [common, publish]
    defaults:
      run:
        shell: pwsh
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish cross-platform manifest
      id: publish
      run: |
        $tagbase = "${{ needs.common.outputs.tagbase }}"
        docker manifest create $tagbase ${{ needs.publish.outputs.linux }} ${{ needs.publish.outputs.win2019 }} ${{ needs.publish.outputs.win2022 }}
        docker manifest push $tagbase
