name: Run Azure Login with OpenID Connect
on: [workflow_dispatch]

permissions:
      id-token: write
      contents: read

env:
  GO_VERSION: '1.16.1'

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Download modules
        run: go mod download
      - name: Build project
        run: go build ./cmd/aks-periscope
      - name: Run the changelog reader
        id: changelog_reader
        uses: ./
      - name: Display output
        run: |
           echo "Version: ${{ steps.changelog_reader.outputs.version }}"
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run Azure CLI commands'
        run: |
          docker build -f ./builder/Dockerfile -t public/aks/periscope .
          docker tag public/aks/periscope ${{ secrets.AZURE_REGISTRY_NAME }}/public/aks/periscope:${{ steps.changelog_reader.outputs.version }}
          echo "acr login attempt"
          az acr login -n tatstest
          echo "acr login attempt success"
          echo "acr push"
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}/public/aks/periscope:${{ steps.changelog_reader.outputs.version }}
          echo "acr push done"