# This is a basic workflow to help you get started with Actions
name: Building and Pushing to GHCR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-2019, windows-2022]
        include:
        - os: ubuntu-latest
          baseimage: 'mcr.microsoft.com/cbl-mariner/distroless/base:2.0'
          tagext: 'mariner2.0'
        - os: windows-2019
          baseimage: 'mcr.microsoft.com/windows/nanoserver:ltsc2019'
          tagext: 'nanoserver2019'
        - os: windows-2022
          baseimage: 'mcr.microsoft.com/windows/nanoserver:ltsc2022'
          tagext: 'nanoserver2022'
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v2
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          path: ./CHANGELOG.md
      - name: Display output
        run: |
          echo "Version: ${{ steps.changelog_reader.outputs.version }}"
          echo "Changes: ${{ steps.changelog_reader.outputs.changes }}"
      # Lowercase my github ownername.
      - name: Set Environment Variables
        run: |
          $owner="${{ github.repository_owner }}".ToLower()
          Add-Content -Path $env:GITHUB_ENV -Value "REPO-OWNER=$owner"

      - name: Login to GitHub Packages OCI Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to ghcr.io 
      # Note the below automatically sets the registry to the local GH registry of the org name. 
      # Currently, for pure gitops reconstructing this runtime setting will require looking at the repository owner of the commit
        run: |
          $tag = "ghcr.io/${{ env.REPO-OWNER }}/aks/periscope:${{ steps.changelog_reader.outputs.version }}-${{ matrix.tagext }}"
          docker build -f ./builder/Dockerfile --build-arg BASE_IMAGE=${{ matrix.baseimage }} -t $tag .
          docker push $tag
